### ISSUE TITLE
`mulMatrixvsMatrixBlockedVectorUnrolled` test fails

### ISSUE THREAD

**Issue by Ledmington** [Styp/java-vbench#2]
Hi there, really nice project and article!
When I clone the repo and run `./gradlew test`, the test `mulMatrixvsMatrixBlockedVectorUnrolled` fails with this message:
```
org.opentest4j.AssertionFailedError: expected: <124.42004> but was: <0.0>
	at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at app//org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:118)
	at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:113)
	at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:856)
	at app//ch.styp.MatrixMulTest.mulMatrixvsMatrixBlockedVectorUnrolled(MatrixMulTest.java:62)
        ...
```

Sometimes, also the test `fmaArrayVectorVsScalar` fails with the message:
```
org.opentest4j.AssertionFailedError: expected: <226.77946> but was: <226.77934>
	at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at app//org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:118)
	at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:113)
	at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:856)
	at app//ch.styp.SumArrayTest.fmaArrayVectorVsScalar(SumArrayTest.java:49)
        ...
```

This happens on java 17.0.8 Temurin, on 18 OpenJDK and on 20 OpenJDK (I have not tested other versions).
I am working on Ubuntu 22.04.3 on an `Intel(R) Core(TM) i7-7700`.

P.S.
Aside from this problem, I notice that the tests for correctness aren't as complete as I think they should be, so I'm working on a PR right now to fix them.

**Comment by Styp** [comment]
I'll commit a major update, just give me a couple of days. :)

**Comment by Ledmington** [comment]
Oh ok. Sorry then :)

**Comment by Styp** [comment]
By the way. if you have suggestions on the completeness... go ahead, I am curious.

**Comment by Ledmington** [comment]
First of all, you don't test all the algorithms you have implemented.
Then, I think you should make sure that the blocked matrix multiplication version produces the same result varying the blocksize (in my fork, I implemented it with junit's parameterized test).
Then, in the vectorized matrix multiplication, you don't perform any "remainder loop" to handle the cases where the matrix's size is not a multiple of the number of lanes. I see that, in `MatrixMulTest`, you wanted to use a prime number as the matrix size but, then, you placed 512 or 256 everywhere.
Lastly, I must admit that this is personal taste so feel free to ignore this advice, I see that you always compare the result of a matrix multiplication algorithm with the naive one as a baseline without checking if the baseline is correct. Whenever I implement some algorithm, even if it's something well-known like the naive matrix multiplication, I always write some tests to make sure that I have implemented it correctly. So, for example in my fork, I multiply some little hard-coded matrices and I multiply a random matrix with the identity.
Hope it helps :)
